### ISSUE TITLE
Multiple identical (?) search results for one actual hit

### ISSUE THREAD

**Issue by dandv** [apollographql/docs-docs#34]
Searching for `formatError at https://docs-docs.netlify.com/docs/docs/ (or at https://www.apollographql.com/docs/apollo-server/) produces the same result three times:

![image](https://user-images.githubusercontent.com/33569/45915756-829e4f00-be0f-11e8-93a3-d85a9168419a.png)

Side note: would be helpful to document the parameters to `formatError` and `formatResponse`.

CC @abernix

**Comment by abernix** [comment]
Thanks for identifying this and reporting it!

Not sure how quickly I'll get to debugging this, but this search configuration lives in the [Algolia Docsearch `docsearch-config`](https://github.com/algolia/docsearch-configs/) repository in [the `apollodata` configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/apollodata.json) and is powered by CSS selectors (namely `H[1-6]`).  It is possible to run those configurations in a local mode and do debugging, but it's been a while since I've done it so not sure how quickly I'd be able to get it up and running.

I'll try to circle back to this ASAP, but don't hesitate to ping me again if this response has gone stale. 😀

**Comment by abernix** [comment]
This no longer occurs.
